#!/bin/zsh
#namegen ver 1.3
#1.0: relase 
#1.1: argument checker 
#1.2: syllables 
#1.3: more syllables added 
if [ -n "$1" ] && [ -n "$2" ]; then

if [ $(($1+$2)) -eq 0 ];

then 
	echo "Usage : namegen [number of words to be generated] [number of syllables to be generated for any given word]";
	exit;
fi
else
echo "Usage : namegen [number of words to be generated] [number of syllables to be generated for any given word]";
exit ;
fi 

vowels=(a e u i o)
constonants=(b c d f g h j k l m n p q r s t v w x y z )
for i in $(seq 1 $1) ;
do 
	echo -n " "
	for i in $(seq 1 $2); 
do	

randomv=$(shuf -i 0-4 -n 1)
randomc=$(shuf -i 0-20 -n 1) 
randomv2=$(shuf -i 0-4 -n 1)
randomc2=$(shuf -i 0-20 -n 1) 
syllable_rnd=$(shuf -i 1-5 -n 1) 

case $syllable_rnd in   
"1")#vc 
echo -n ${vowels[randomv]} && echo -n ${constonants[randomc]} 
;;
"2")#cv
echo -n ${constonants[randomc]} && echo -n ${vowels[randomv]} 
;;
"3") #cvc 
echo -n ${constonants[randomc]} && echo -n ${vowels[randomv]} && echo -n ${constonants[randomc2]}  
;; 
"4") #vcv 
echo -n ${vowels[randomv]} && echo -n ${constonants[randomc]} &&  echo -n ${vowels[randomv2]}  
;;
"5") #cvv 
echo -n ${constonants[randomc]} && echo -n ${vowel[randomv]}  && echo -n ${vowels[randomv2]} 
;;
esac
done
done
